### ISSUE TITLE
push-docker-image does not work either as a job or as a command

### ISSUE THREAD

**Issue by markku63** [CircleCI-Public/heroku-orb#18] opened 2020-08-27 08:31 UTC
**Orb Version**
1.2.2

**Describe the bug**
First, I tried to use the heroku/push-docker-image job, and it failed  in the "Login to Heroku Docker image registry" step with error:
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 ▸    Login failed with: 1
```
Some Googling revealed that this is caused by a missing `setup_remote_docker` step, so I tried my own job with that step included before the heroku/push-docker-image command. This time it failed at "Push Docker image to Heroku" with:
```
#!/bin/bash -eo pipefail
heroku container:push -a $HEROKU_APP_NAME \

web

 ▸    Error: Requires either
 ▸    --recursive or one or
 ▸    more process types


Exited with code exit status 1

CircleCI received exit code 1
```
There appears to be an extra linefeed (or a missing backslash) in the command.

**To Reproduce**
Set up a CircleCI project following my public GitHub repo at https://github.com/markku63/mooc-wepa-20-projekti
Define the HEROKU_APP_NAME and HEROKU_API_KEY environment variables.

**Expected behavior**
The project builds and deploys to Heroku.

**Additional context**

**Comment by n2taylor** [comment] 2020-09-17 19:36
I've encountered this issue with the backslash too, it's definitely [missing](https://github.com/CircleCI-Public/heroku-orb/blob/master/src/commands/push-docker-image.yml#L39). As a workaround/hack you can pass the desired CLI args inside `HEROKU_APP_NAME`

**Comment by eerison** [comment] 2020-11-22 20:45
the same here 😕

**Comment by sahilrajput03** [comment] 2021-02-01 08:24
Is this added to latest orb image yet.?

**Comment by eerison** [comment] 2021-02-01 08:40
Hi @sahilrajput03 I'll test the latest version and I'll post here the result
Thanks :)

**Comment by dsayling** [comment] 2021-02-01 17:47
Fix is in version `1.2.5` of the orb.

**Closed by dsayling** 2021-02-01 17:47 UTC
Labels: bug

**Comment by sahilrajput03** [comment] 2021-02-02 07:09
Thanks a lot!

**Comment by eerison** [comment] 2021-02-06 13:06
I guess it does't  resolve this issue: https://github.com/eerison/myprofile/pull/310/files

```
#!/bin/bash -eo pipefail
heroku container:login
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 ▸    Login failed with: 1


Exited with code exit status 1
CircleCI received exit code 1
```

the problem is authentication is not working ....

But why ? 😕

**Comment by sahilrajput03** [comment] 2021-02-07 07:06
This problem can be easily resolved by using this knowledge!!.

![IMG_20210207_123540.jpg](https://user-images.githubusercontent.com/31458531/107139425-086bb800-6941-11eb-96e1-8e0b8fcf6dfb.jpg)

**Comment by sahilrajput03** [comment] 2021-02-07 07:08
> I guess it does't  resolve this issue
> PR: https://github.com/eerison/myprofile/pull/310/files
> pipeline: https://app.circleci.com/pipelines/github/eerison/myprofile/518/workflows/03dd35c0-3f2d-4e95-828e-e5ddc538bbe8/jobs/1041
> 
> ```
> #!/bin/bash -eo pipefail
> heroku container:login
> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
>  ▸    Login failed with: 1
> 
> 
> Exited with code exit status 1
> CircleCI received exit code 1
> ```
> 
> the problem is authentication is not working ....
> 
> But why ? 😕 
The error clearly says cannot connect to docker daemon, its not at all related to authentication, the problem is docker isn't installed, you install docker using setup-remote-docker instruction in ur config.yml file as heroku underneath uses docker.

**Comment by sahilrajput03** [comment] 2021-02-07 07:09
The image is from this url: https://circleci.com/docs/2.0/building-docker-images/
